/**
 * Better Auth (plan §5.2, §14 D7): email/password + conditional GitHub/Google
 * OAuth, organization plugin with roles and invites.
 *
 * Table mapping is handled by `usePlural` + explicit modelNames so Better
 * Auth writes into our plan-§7 tables (`users`, `sessions`, `accounts`,
 * `verifications`, `organizations`, `memberships`, `invites`) — see
 * drizzle/schema.ts for the column contract.
 */
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { bearer, organization } from "better-auth/plugins";
import { createAccessControl } from "better-auth/plugins/access";
import { nextCookies } from "better-auth/next-js";
import { capabilities, getEnv } from "@/shared/config/env";
import { getPgDb } from "@/shared/db/pg";
import * as dbSchema from "@/shared/db/schema";

/**
 * Plan §5.2 roles. Statements mirror the organization plugin's default
 * statements so admin/owner semantics are preserved; annotator/reviewer get no
 * org-administration rights (their gating happens in `shared/domain/auth.ts`
 * `can()` against annotation/review actions, not Better Auth).
 */
const ac = createAccessControl({
  organization: ["update", "delete"],
  member: ["create", "update", "delete"],
  invitation: ["create", "cancel"],
  team: ["create", "update", "delete"],
  ac: ["create", "read", "update", "delete"],
} as const);

const adminRole = ac.newRole({
  organization: ["update"],
  member: ["create", "update", "delete"],
  invitation: ["create", "cancel"],
  team: ["create", "update", "delete"],
  ac: ["create", "read", "update", "delete"],
});

export function createAuth() {
  const env = getEnv();
  const caps = capabilities(env);

  return betterAuth({
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    advanced: {
      database: {
        // Plan §7 ids are uuidv7 generated by our drizzle `pk()` defaults;
        // "uuid" mode makes Better Auth defer id generation to the column.
        generateId: "uuid",
      },
    },
    database: drizzleAdapter(getPgDb(), {
      provider: "pg",
      usePlural: true,
      schema: dbSchema,
    }),
    emailAndPassword: {
      enabled: true,
    },
    socialProviders: {
      ...(caps.oauthGithub
        ? {
            github: {
              clientId: env.GITHUB_CLIENT_ID as string,
              clientSecret: env.GITHUB_CLIENT_SECRET as string,
            },
          }
        : {}),
      ...(caps.oauthGoogle
        ? {
            google: {
              clientId: env.GOOGLE_CLIENT_ID as string,
              clientSecret: env.GOOGLE_CLIENT_SECRET as string,
            },
          }
        : {}),
    },
    plugins: [
      // Accept `Authorization: Bearer <session-token>` (tests, server callers).
      bearer(),
      // modelName bases chosen so `usePlural` lands on our §7 table names:
      // membership → memberships, invite → invites, organization → organizations.
      organization({
        // Plan §5.2: org creator is an admin (not Better Auth's default owner).
        creatorRole: "admin",
        roles: {
          admin: adminRole,
          annotator: ac.newRole({}),
          reviewer: ac.newRole({}),
        },
        schema: {
          member: { modelName: "membership" },
          invitation: { modelName: "invite" },
        },
      }),
      nextCookies(),
    ],
  });
}

export const auth = createAuth();
export type Auth = typeof auth;
