import Link from "next/link";
import { listLabels } from "@/shared/lib/fixtures";

const STATUS_STYLES: Record<string, string> = {
  queue: "border-sky-300 bg-sky-50 text-sky-800",
  review: "border-amber-300 bg-amber-50 text-amber-800",
  export: "border-emerald-300 bg-emerald-50 text-emerald-800",
};

function NavCard({ href, name, desc, tone }: { href: string; name: string; desc: string; tone: string }) {
  return (
    <Link href={href} className={`block rounded border p-3 transition hover:brightness-95 ${tone}`}>
      <p className="text-sm font-medium">{name}</p>
      <p className="mt-1 text-xs opacity-80">{desc}</p>
    </Link>
  );
}

export default function LabelsPage() {
  const labels = listLabels();
  const totalGt = labels.reduce((n, l) => n + l.gtCount, 0);
  const totalPred = labels.reduce((n, l) => n + l.predCount, 0);

  return (
    <main className="mx-auto max-w-5xl px-6 py-8">
      <p className="mb-2 inline-block rounded border border-amber-300 bg-amber-50 px-2 py-1 text-xs font-medium text-amber-800">
        Research prototype, not for clinical use
      </p>
      <h1 className="text-2xl font-semibold tracking-tight">LabelForge</h1>
      <p className="mt-1 max-w-3xl text-sm text-zinc-600">
        Draw and resize FDI + pathology boxes, submit sets for review with inter-annotator
        agreement, triage an active-learning queue, and export YOLO/COCO datasets.
      </p>

      <section className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3">
        <NavCard
          href="/labels/queue"
          name="Active-learning queue"
          desc="Heuristic uncertainty ordering over unlabeled images"
          tone={STATUS_STYLES.queue ?? ""}
        />
        <NavCard
          href="/labels/review"
          name="Review"
          desc="Adjudicate submitted sets; Cohen's κ agreement"
          tone={STATUS_STYLES.review ?? ""}
        />
        <NavCard
          href="/labels/export"
          name="Export"
          desc="YOLO txt / COCO json from approved + submitted sets"
          tone={STATUS_STYLES.export ?? ""}
        />
      </section>

      <section className="mt-8">
        <h2 className="text-sm font-medium text-zinc-700">Images</h2>
        <div className="mt-2 grid grid-cols-1 gap-4 sm:grid-cols-2">
          {labels.map((l) => (
            <Link
              key={l.id}
              href={`/labels/${l.id}`}
              className="group rounded border border-zinc-200 bg-white p-3 transition hover:border-zinc-400"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={l.image_path}
                alt={`Image ${l.id} (${l.source_file})`}
                className="w-full rounded border border-zinc-100 bg-zinc-950"
                loading="lazy"
              />
              <div className="mt-2 flex items-baseline justify-between gap-2">
                <p className="font-mono text-sm font-medium">image {l.id}</p>
                <p className="text-xs text-zinc-500">{l.source_file}</p>
              </div>
              <div className="mt-1 flex flex-wrap gap-1.5 text-xs">
                <span className="rounded border border-emerald-300 bg-emerald-50 px-1.5 py-0.5 text-emerald-800">
                  {l.gtCount} GT boxes
                </span>
                <span className="rounded border border-sky-300 bg-sky-50 px-1.5 py-0.5 text-sky-800">
                  {l.predCount} pre-labels
                </span>
                <span className="rounded border border-zinc-300 bg-zinc-50 px-1.5 py-0.5 text-zinc-600">
                  {l.width}×{l.height}
                </span>
              </div>
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-8 rounded border border-zinc-200 bg-zinc-50 p-4 text-xs leading-relaxed text-zinc-600">
        <p className="font-medium text-zinc-800">Data provenance</p>
        <p className="mt-1">
          {labels.length} images, {totalGt} consensus GT boxes, {totalPred} stored YOLO
          pre-labels — all generated by <span className="font-mono">scripts/generate_m5_labels.py</span>{" "}
          from the real DENTEX COCO annotations and real <span className="font-mono">yolo_cv_best</span>{" "}
          inference (ADR-0005). GT is cross-checked against the Trace Explorer fixtures in CI.
        </p>
        <p className="mt-1">
          DENTEX is licensed CC-BY-NC-SA-4.0; images here are downscaled derivatives for
          non-commercial research use.
        </p>
      </section>
    </main>
  );
}
