/**
 * M4 port: pixel-level image tools.
 * Sources: dental_agent/tools/{contrast,windowing,denoise,contralateral}.py
 *
 * Parity contract (fixtures/goldens/m4_tools.json, generated by real PIL/cv2):
 * - enhanceContrast: EXACT — PIL algorithm = L-convert (Rec.601, round-to-
 *   nearest int), degenerate mean = int(mean+0.5), Image.blend which
 *   truncates toward zero after clamping.
 * - windowLevel: EXACT — L-convert, clip to window, linear scale to 0-255,
 *   np.astype(uint8) truncates (not rounds), output RGB.
 * - denoiseMedian: EXACT — cv2.medianBlur semantics, per-channel, k odd,
 *   BORDER_REPLICATE.
 * - denoiseBilateral: APPROXIMATE — cv2.bilateralFilter uses a quantized
 *   city-block color distance + lookup tables; this port uses the standard
 *   Gaussian range-weight formulation. Tolerance-tested (see ADR-0004).
 * - contralateralComposite: EXACT geometry port.
 */

export type Rgb = Uint8Array; // 3 bytes per pixel, row-major

/**
 * The registry tools that return an IMAGE (plan §4.4) — everything else
 * (`locate_tooth`, `fdi_label`, `nudge_crop`) returns data already carried in
 * the call record. The trace viewer uses this to decide between a stored
 * artifact and the §9 placeholder-with-args fallback.
 */
export const IMAGE_OUTPUT_TOOLS = [
  "zoom_crop",
  "window_level",
  "denoise",
  "contralateral_compare",
  "enhance_contrast",
] as const;

export function isImageOutputTool(toolName: string): boolean {
  return (IMAGE_OUTPUT_TOOLS as readonly string[]).includes(toolName);
}

/** PIL integer Rec.601 luma with round-to-nearest (bit-exact vs PIL.convert("L")). */
export function luma8(r: number, g: number, b: number): number {
  return (19595 * r + 38470 * g + 7471 * b + 32768) >> 16;
}

/** PIL Contrast: degenerate mean on the L image, then blend with truncation. */
export function enhanceContrast(src: Rgb, factor: number): Rgb {
  const n = src.length;
  const px = n / 3;
  let sum = 0;
  for (let i = 0; i < px; i++) {
    sum += luma8(src[3 * i]!, src[3 * i + 1]!, src[3 * i + 2]!);
  }
  // int(mean + 0.5), positive so truncation == floor
  const mean = Math.floor(sum / px + 0.5);
  const out = new Uint8Array(n);
  for (let i = 0; i < n; i++) {
    const v = mean + factor * (src[i]! - mean);
    out[i] = v <= 0 ? 0 : v >= 255 ? 255 : Math.floor(v);
  }
  return out;
}

export const WINDOW_PRESETS: Record<string, { center: number; width: number }> = {
  bone: { center: 128, width: 100 },
  enamel: { center: 200, width: 100 },
  soft_tissue: { center: 80, width: 150 },
  metal_reduction: { center: 100, width: 200 },
};

/** Port of tool_window_level: L-convert, clip, linear scale, truncate, RGB out. */
export function windowLevel(
  src: Rgb,
  preset = "bone",
  centerOverride?: number,
  widthOverride?: number,
): Rgb {
  const p = WINDOW_PRESETS[preset] ?? WINDOW_PRESETS.bone!;
  const center = centerOverride ?? p.center;
  const width = Math.max(1.0, widthOverride ?? p.width);
  const lo = center - width / 2;
  const hi = center + width / 2;
  const n = src.length;
  const out = new Uint8Array(n);
  for (let i = 0; i < n; i += 3) {
    const g = luma8(src[i]!, src[i + 1]!, src[i + 2]!);
    const clipped = g < lo ? lo : g > hi ? hi : g;
    const scaled = hi > lo ? ((clipped - lo) / (hi - lo)) * 255 : 0;
    const v = scaled <= 0 ? 0 : scaled >= 255 ? 255 : Math.floor(scaled);
    out[i] = out[i + 1] = out[i + 2] = v;
  }
  return out;
}


/** ksize for median method: int(round(3 + strength*10)), forced odd (cv2 requirement). */
function medianKsize(strength: number): number {
  const s = Math.max(0, Math.min(1, strength));
  let k = Math.round(3 + s * 10);
  if (k % 2 === 0) k += 1;
  return Math.max(3, k);
}

/** Port of tool_denoise(method="median"): per-channel median, replicate border. */
export function denoiseMedian(src: Rgb, w: number, h: number, strength = 0.6): Rgb {
  const s = Math.max(0, Math.min(1, strength));
  const k = medianKsize(s);
  const r = (k - 1) / 2;
  const out = new Uint8Array(src.length);
  const win: number[] = [];
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      for (let c = 0; c < 3; c++) {
        win.length = 0;
        for (let dy = -r; dy <= r; dy++) {
          const yy = Math.min(h - 1, Math.max(0, y + dy));
          for (let dx = -r; dx <= r; dx++) {
            const xx = Math.min(w - 1, Math.max(0, x + dx));
            win.push(src[3 * (yy * w + xx) + c]!);
          }
        }
        win.sort((a, b) => a - b);
        out[3 * (y * w + x) + c] = win[win.length >> 1]!;
      }
    }
  }
  return out;
}

/** Port of tool_denoise(method="bilateral"): cv2-exact formula (ADR-0004):
 * range weight = exp(-(L1_color)²/(2·σColor²)), circular spatial kernel
 * (r ≤ radius), BORDER_REFLECT_101, σColor=σSpace=round(20+s·180). */
export function denoiseBilateral(src: Rgb, w: number, h: number, strength = 0.6): Rgb {
  const s = Math.max(0, Math.min(1, strength));
  const d = Math.round(5 + s * 20);
  const radius = Math.max(1, Math.floor(d / 2));
  const sigma = Math.round(20 + s * 180);
  const twoSigmaSq = 2 * sigma * sigma;
  // cv2 BORDER_REFLECT_101
  const r101 = (i: number, n: number): number => {
    if (n === 1) return 0;
    while (i < 0 || i >= n) {
      if (i < 0) i = -i;
      if (i >= n) i = 2 * n - 2 - i;
    }
    return i;
  };
  // spatial kernel table (circular), skip out-of-radius corners + center handled below
  const spTable = new Float64Array((2 * radius + 1) * (2 * radius + 1));
  for (let dy = -radius; dy <= radius; dy++) {
    for (let dx = -radius; dx <= radius; dx++) {
      const rr2 = dx * dx + dy * dy;
      spTable[(dy + radius) * (2 * radius + 1) + (dx + radius)] =
        rr2 > radius * radius ? 0 : Math.exp(-rr2 / twoSigmaSq);
    }
  }
  // range table over L1 color distance 0..765
  const l1Table = new Float64Array(766);
  for (let i = 0; i <= 765; i++) l1Table[i] = Math.exp(-(i * i) / twoSigmaSq);
  const out = new Uint8Array(src.length);
  const stride = 2 * radius + 1;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const idx = 3 * (y * w + x);
      const pr = src[idx]!, pg = src[idx + 1]!, pb = src[idx + 2]!;
      let wSum = 0, wr = 0, wg = 0, wb = 0;
      for (let dy = -radius; dy <= radius; dy++) {
        const yy = r101(y + dy, h);
        const row = 3 * yy * w;
        for (let dx = -radius; dx <= radius; dx++) {
          const sp = spTable[(dy + radius) * stride + (dx + radius)]!;
          if (sp === 0) continue;
          const j = row + 3 * r101(x + dx, w);
          const l1 = Math.abs(src[j]! - pr) + Math.abs(src[j + 1]! - pg) + Math.abs(src[j + 2]! - pb);
          const wgt = sp * l1Table[l1]!;
          wSum += wgt;
          wr += wgt * src[j]!;
          wg += wgt * src[j + 1]!;
          wb += wgt * src[j + 2]!;
        }
      }
      const inv = 1 / wSum;
      const v0 = Math.round(wr * inv), v1 = Math.round(wg * inv), v2 = Math.round(wb * inv);
      out[idx] = v0 < 0 ? 0 : v0 > 255 ? 255 : v0;
      out[idx + 1] = v1 < 0 ? 0 : v1 > 255 ? 255 : v1;
      out[idx + 2] = v2 < 0 ? 0 : v2 > 255 ? 255 : v2;
    }
  }
  return out;
}

export interface RgbImage { data: Rgb; w: number; h: number }

/** Port of tool_contralateral_compare (exact geometry; returns composite image). */
export function contralateralComposite(
  src: Rgb, w: number, h: number, bbox: number[], quadrant: number,
): RgbImage {
  if (bbox.length !== 4) throw new RangeError("bbox must be [x, y, w, h]");
  if (![1, 2, 3, 4].includes(quadrant)) throw new RangeError("quadrant must be 1-4 (FDI convention).");
  const [bx, by, bw, bh] = bbox.map((v) => Math.trunc(v)) as [number, number, number, number];
  const midY = Math.trunc(h / 2.0); // int(img_h / 2.0)

  const x1 = Math.max(0, bx), y1 = Math.max(0, by);
  const x2 = Math.min(w, bx + bw), y2 = Math.min(h, by + bh);
  if (x2 <= x1 || y2 <= y1) return { data: src.slice(), w, h }; // invalid -> full copy

  const targetW = x2 - x1, targetH = y2 - y1;
  const mirrorX2 = w - bx;
  const mirrorX1 = mirrorX2 - bw;
  const mx1 = Math.max(0, Math.trunc(mirrorX1));
  const mx2 = Math.min(w, Math.trunc(mirrorX2));
  const my1 = quadrant <= 2 ? Math.max(0, by) : Math.max(midY, by);
  const my2 = quadrant <= 2 ? Math.min(midY, by + bh) : Math.min(h, by + bh);

  // copy target region
  const target = new Uint8Array(targetW * targetH * 3);
  for (let y = 0; y < targetH; y++) {
    const s = 3 * ((y1 + y) * w + x1);
    target.set(src.subarray(s, s + targetW * 3), 3 * y * targetW);
  }
  if (mx2 <= mx1 || my2 <= my1) return { data: target, w: targetW, h: targetH };

  const mirrorW = mx2 - mx1, mirrorH = my2 - my1;
  const compW = targetW + mirrorW + 10;
  const compH = Math.max(targetH, mirrorH);
  const out = new Uint8Array(compW * compH * 3); // black canvas
  for (let y = 0; y < targetH; y++) {
    out.set(target.subarray(3 * y * targetW, 3 * (y + 1) * targetW), 3 * y * compW);
  }
  for (let y = 0; y < mirrorH; y++) {
    const s = 3 * ((my1 + y) * w + mx1);
    out.set(src.subarray(s, s + mirrorW * 3), 3 * (y * compW + targetW + 10));
  }
  return { data: out, w: compW, h: compH };
}

